# Site settings
# These are used to personalize your new site.
title: Robert B Squires # your name here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br /> elements if you don't need line breaks)
  Coder. Gear Head. Gypsy Soul.<br />
  In partial fulfillment of the requirements for the degree of
  Bachelor of Science in Computer Science, minoring in Web Development (December 2023)
  <br /><br />
  <a href="pdf/Robert B. Squires III Resume.pdf" target="_blank">View My Resume</a>
  <br /><br />
  <a href="https://www.linkedin.com/in/robert-squires-b0b554291/" target="_blank">View My LinkedIn Profile</a>
  <details>
	  <summary><h3>My Coding Journey</h3></summary>
      I started my coding journey as a Computer Science student with a passion to learn everything I could about making programs that would be useful.
      Since I use an iPhone, I wanted to teach myself iOS development with a dream to build my own app.
      Having a background as a mechanic, I chose to make an OBD-II application to bring together my love of vehicles and the technologies I have been learning throughout my education in Computer Science.
      I enjoy programming in C++ and Java, but have also grown to enjoy using Swift and SwiftUI for programming specifically for Apple products.
      I hope to continue growing my developer skill as a whole, as well as become more proficient in iOS,iPadOS, and macOS development.
  </details>

repository: "csci-csu/csci-portfolio"
github_username: rbsquires # update with your username
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

# Build setting
theme: jekyll-theme-minimal

